DROP TABLE IF EXISTS WORKFLOW;
CREATE TABLE WORKFLOW ( ID INT NOT NULL AUTO_INCREMENT ,PRIMARY KEY (ID) , NAME VARCHAR(999) );
DROP TABLE IF EXISTS TASK;
CREATE TABLE TASK ( ID INT NOT NULL AUTO_INCREMENT ,PRIMARY KEY (ID) , NAME VARCHAR(999) , TASK_TYPE VARCHAR(999) );
DROP TABLE IF EXISTS WORKFLOW_TASK;
CREATE TABLE WORKFLOW_TASK ( WF_ID INT , TASK_ID INT , TASK_SEQ INT );
DROP TABLE IF EXISTS TASK_IO;
CREATE TABLE TASK_IO ( TASK_ID INT , IO_ID INT , IO_SEQ INT , IO_TYPE VARCHAR(999) );
DROP TABLE IF EXISTS IO_INFO;
CREATE TABLE IO_INFO ( ID INT NOT NULL AUTO_INCREMENT ,PRIMARY KEY (ID) , STORAGE_TYPE VARCHAR(999) , FILE_PATH VARCHAR(999) , DB_SCHEMA VARCHAR(999) , TABLE_NAME VARCHAR(999) , PARTITIONC_COLS VARCHAR(999) , DATA_NAME VARCHAR(999) , CONN_TYPE VARCHAR(999) , KERBOROS VARCHAR(999) , JNDI VARCHAR(999) , JDBC_URL VARCHAR(999) , USER VARCHAR(999) , PASSWORD VARCHAR(999) , JDBC_DRIVER_CLASS VARCHAR(999) );
DROP TABLE IF EXISTS JOB;
CREATE TABLE JOB ( JOB_ID INT NOT NULL AUTO_INCREMENT ,PRIMARY KEY (JOB_ID) , JOB_UID VARCHAR(999) , WF_ID INT , TASK_ID INT , TASK_SEQ INT , SCHEDULE_TIME TIMESTAMP , SUBMIT_TIME TIMESTAMP , START_TIME TIMESTAMP , END_TIME TIMESTAMP , LAST_UPD_TIME TIMESTAMP , STATUS VARCHAR(999) , RESPONSE_JSON TEXT );
DROP TABLE IF EXISTS DQ_SUMMARY;
CREATE TABLE DQ_SUMMARY ( JOB_ID INT , JOB_UID VARCHAR(999) , WF_ID INT , TASK_ID INT , DATA_NAME VARCHAR(999) , COLUMN_NAME VARCHAR(999) , DQ_ERROR_CODE VARCHAR(999) , TOTAL_REC_COUNT INT , FAILED_REC_COUNT INT , SUCCESS_REC_COUNT INT , UPD_TIME INT );
DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER ( ID INT , NAME VARCHAR(100) , EMAIL VARCHAR(100) , CREATED_DATE DATE );
DROP TABLE IF EXISTS DATA;
CREATE TABLE DATA ( NAME VARCHAR(999) , TANSFORM_TYPE VARCHAR(999) , TRANSFORM_INPUTS VARCHAR(999) , FITER_FORMULA VARCHAR(999) , COMPOSITE_JOIN_FORMULA VARCHAR(999) , ING_FILE_READ_FORMULA VARCHAR(999) );
DROP TABLE IF EXISTS DATA_COLUMN;
CREATE TABLE DATA_COLUMN ( DATA_NAME VARCHAR(999) , NAME VARCHAR(999) , SEQ INT , DATA_TYPE VARCHAR(999) , ENRICH_FORMULA VARCHAR(999) , AGGR_FORMULA VARCHAR(999) , AGGR_DM_TYPE VARCHAR(999) , SET_OP_FORMULA VARCHAR(999) , READ_FORMAT VARCHAR(999) , WRITE_FORMAT VARCHAR(999) , LOOKUP_IO_TYPE VARCHAR(999) , ING_COL_READ_FORMULA VARCHAR(999) , DQ_ERROR_CODE VARCHAR(999) , DQ_ERROR_FORMULA VARCHAR(999) , DISPOSITION_FORMULA VARCHAR(999) );


delete from DATA where NAME='DATA1';
insert into DATA(NAME,ING_FILE_READ_FORMULA) 
values('DATA1','
LAYOUT(
					HEADER_LINE_COUNT(2),
					HEADER_IDENTIFIER("H"),
					TAILOR_LINE_COUNT(2),
					TAILOR_IDENTIFIER("T"),
					RECORD_IDENTIFIER("D"),
					RECORD_DELIMITER("|"),
					CHECK_COLUMN_COUNT(),
					TRIM_SPACES()
				)
');
delete from DATA_COLUMN where DATA_NAME='DATA1';
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE) values('DATA1','ID',1,'I');
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE) values('DATA1','AGE',2,'I');
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE,ING_COL_READ_FORMULA) values('DATA1','GENDER',3,'S','LAYOUT(REPLACE("M","Male"),REPLACE("F","Female"))');
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE,ING_COL_READ_FORMULA) values('DATA1','INCOME',4,'N','LAYOUT(STRIP_CHARS("$#{},"))');
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE,ING_COL_READ_FORMULA) values('DATA1','STATE',5,'S','LAYOUT(UPPER_CASE())');
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE) values('DATA1','HIGHT',6,'N');	
insert into DATA_COLUMN(DATA_NAME,NAME,SEQ,DATA_TYPE) values('DATA1','WEIGHT',7,'N');


--trigger
delete from WORKFLOW where NAME='WorkFlow1_IngestRaw';
insert into WORKFLOW(NAME) values('WorkFlow1_IngestRaw');

delete from TASK where NAME='Task1_IngestRaw';
insert into TASK(NAME,TASK_TYPE) values('Task1_IngestRaw','INGEST');
delete from WORKFLOW_TASK where WF_ID=(select ID from WORKFLOW where NAME='WorkFlow1_IngestRaw');
insert into WORKFLOW_TASK(WF_ID,TASK_ID,TASK_SEQ) select (select ID from WORKFLOW where NAME='WorkFlow1_IngestRaw') as WF_ID,(select ID from TASK where NAME='Task1_IngestRaw') as TASK_ID,1 as TASK_SEQ;
delete from IO_INFO where STORAGE_TYPE='RAW' and FILE_PATH='/tmp/data/raw/rawdata.txt' and DATA_NAME='DATA1';
insert into IO_INFO(STORAGE_TYPE,FILE_PATH,DATA_NAME) values('RAW','/tmp/data/raw/rawdata.txt','DATA1');
delete from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingested.csv';
--delete from IO_INFO where STORAGE_TYPE='AVRO' and FILE_PATH='/tmp/data/curated/rawdata_ingested.avro';
insert into IO_INFO(STORAGE_TYPE,FILE_PATH) values('CSV','/tmp/data/curated/rawdata_ingested.csv');
--insert into IO_INFO(STORAGE_TYPE,FILE_PATH) values('AVRO','/tmp/data/curated/rawdata_ingested.avro');
delete from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingestion_errors.csv';
insert into IO_INFO(STORAGE_TYPE,FILE_PATH) values('CSV','/tmp/data/curated/rawdata_ingestion_errors.csv');
delete from TASK_IO where 1=1 
	and TASK_ID=(select ID from TASK where NAME='Task1_IngestRaw') 
	and IO_ID=(select ID from IO_INFO where STORAGE_TYPE='RAW' and FILE_PATH='/tmp/data/raw/rawdata.txt' and DATA_NAME='DATA1')
	and IO_SEQ=1
	and IO_TYPE='INPUT';
insert into TASK_IO(TASK_ID,IO_ID,IO_SEQ,IO_TYPE) select  
	(select ID from TASK where NAME='Task1_IngestRaw') as TASK_ID,
	(select ID from IO_INFO where STORAGE_TYPE='RAW' and FILE_PATH='/tmp/data/raw/rawdata.txt' and DATA_NAME='DATA1') as IO_ID,
	1 as IO_SEQ,
	'INPUT' as IO_TYPE;
delete from TASK_IO where 1=1 
	and TASK_ID=(select ID from TASK where NAME='Task1_IngestRaw') 
	and IO_ID=(select ID from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingested.csv')
--	and IO_ID=(select ID from IO_INFO where STORAGE_TYPE='AVRO' and FILE_PATH='/tmp/data/curated/rawdata_ingested.avro')
	and IO_SEQ=2
	and IO_TYPE='OUTPUT';
insert into TASK_IO(TASK_ID,IO_ID,IO_SEQ,IO_TYPE) select  
	(select ID from TASK where NAME='Task1_IngestRaw') as TASK_ID,
	(select ID from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingested.csv') as IO_ID,
--	(select ID from IO_INFO where STORAGE_TYPE='AVRO' and FILE_PATH='/tmp/data/curated/rawdata_ingested.avro') as IO_ID,
	2 as IO_SEQ,
	'OUTPUT' as IO_TYPE;
delete from TASK_IO where 1=1 
	and TASK_ID=(select ID from TASK where NAME='Task1_IngestRaw') 
	and IO_ID=(select ID from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingestion_errors.csv')
	and IO_SEQ=3
	and IO_TYPE='REJECT';
insert into TASK_IO(TASK_ID,IO_ID,IO_SEQ,IO_TYPE) select  
	(select ID from TASK where NAME='Task1_IngestRaw') as TASK_ID,
	(select ID from IO_INFO where STORAGE_TYPE='CSV' and FILE_PATH='/tmp/data/curated/rawdata_ingestion_errors.csv') as IO_ID,
	3 as IO_SEQ,
	'REJECT' as IO_TYPE;
delete from JOB where JOB_UID='JOB_43AD70EDCDBB4C34A18CC475A08700BB';
insert into JOB(JOB_UID,WF_ID,TASK_ID,TASK_SEQ,SCHEDULE_TIME,LAST_UPD_TIME,STATUS)
select 'JOB_43AD70EDCDBB4C34A18CC475A08700BB' as JOB_UID, 
		(select ID from WORKFLOW where NAME='WorkFlow1_IngestRaw') as WF_ID,
		(select ID from TASK where NAME='Task1_IngestRaw') as TASK_ID,
		1 as TASK_SEQ,
		now() SCHEDULE_TIME,
		now() LAST_UPD_TIME,
		'SCHEDULED'
		;


